### ISSUE TITLE
setuptools v72.0.0 Removed TestCommand

### ISSUE THREAD

**Issue by hasan-ozkok** [saxix/django-concurrency#251]
In latest version of the setuptools django-concurrency package can not be installed.
`ownloading django-concurrency-2.5.tar.gz (59 kB)
  Preparing metadata ([setup.py](http://setup.py/)): started
  Preparing metadata ([setup.py](http://setup.py/)): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python [setup.py](http://setup.py/) egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ty1p15fa/django-concurrency_c24557b5721d40af921893bd052d7ca4/setup.py", line 7, in <module>
          from setuptools.command.test import test as TestCommand
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]`
      
     https://setuptools.pypa.io/en/stable/history.html#v72-0-0

**Comment by scorpp** [comment]
workaround options https://stackoverflow.com/a/78806669/679052

**Comment by ozkokhasan** [comment]
solved 2.6.0
