### ISSUE TITLE
Installation fails on Python 3.7.0b1

### ISSUE THREAD

**Issue by blueyed** [saxix/django-concurrency#88]
Installation fails on Python 3.7.0b1.

```
% pip install django-concurrency
Collecting django-concurrency==1.4 (from -r requirements/base.txt (line 29))
  Using cached django-concurrency-1.4.tar.gz                                                                                                                 
    Complete output from command python setup.py egg_info:
                                                                                                                                                       
    Installed /tmp/easy_install-s5x7gw65/pytest-runner-3.0/.eggs/setuptools_scm-1.15.7-py3.7.egg
    zip_safe flag not set; analyzing archive contents...                                                                                                  
    Traceback (most recent call last):
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved                
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield                                    
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 278, in run
        return func()        
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 47, in _execfile     
        exec(code, globals, locals)                            
      File "/tmp/easy_install-s5x7gw65/pytest-runner-3.0/setup.py", line 68, in <module>                                                                              
        'License :: OSI Approved :: BSD License',     
      File "…/pyenv/3.7.0b1/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "…/pyenv/3.7.0b1/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "…/pyenv/3.7.0b1/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 209, in run
        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
        return analyze_egg(self.bdist_dir, self.stubs)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
        safe = scan_module(egg_dir, base, name, stubs) and safe
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
        code = marshal.load(f)
    ValueError: bad marshal data (unknown type code)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h66zo67p/django-concurrency/setup.py", line 83, in <module>
        platforms=['any'],
      File "…/pyenv/3.7.0b1/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)                                         
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)                                             
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)                                                           
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 251, in run_setup
        raise
      File "…/pyenv/3.7.0b1/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "…/pyenv/3.7.0b1/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-s5x7gw65/pytest-runner-3.0/setup.py", line 68, in <module>
        'License :: OSI Approved :: BSD License',
      File "…/pyenv/3.7.0b1/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "…/pyenv/3.7.0b1/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "…/pyenv/3.7.0b1/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 209, in run
        os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
        return analyze_egg(self.bdist_dir, self.stubs)
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
        safe = scan_module(egg_dir, base, name, stubs) and safe
      File "…/pyenv/3.7.0b1/envs/tmp-3.7.0b1-project-1FLUQD/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
        code = marshal.load(f)
    ValueError: bad marshal data (unknown type code)
```

**Comment by saxix** [comment]
closing this issue as tests succeed on travis with python 3.7 stable
